### ISSUE TITLE
کاربرد

### ISSUE THREAD

**Issue by yoosefsk** [msasanmh/PersianSubtitleFixes#3]
سلام آقا خسته نباشید 
من انگلیسی قوی ندارم میشه لطف کنید خودتون بگید این برنامه چیکار می‌کنه ؟؟؟ ویدیو بهش میدی زیرنویس درست می‌کنه برای هر ویدیویی!!!

**Comment by msasanmh** [comment]
> سلام آقا خسته نباشید 
> من انگلیسی قوی ندارم میشه لطف کنید خودتون بگید این برنامه چیکار می‌کنه ؟؟؟ ویدیو بهش میدی زیرنویس درست می‌کنه برای هر ویدیویی!!!

نه، زیرنویس فارسی بهش میدی و اشکالات زیرنویس رو برات برطرف می‌کنه.

**Comment by yoosefsk** [comment]
> > سلام آقا خسته نباشید 
> > من انگلیسی قوی ندارم میشه لطف کنید خودتون بگید این برنامه چیکار می‌کنه ؟؟؟ ویدیو بهش میدی زیرنویس درست می‌کنه برای هر ویدیویی!!!
> 
> نه، زیرنویس فارسی بهش میدی و اشکالات زیرنویس رو برات برطرف می‌کنه. 

خیلی ممنون جسارتا شما راهی بلد نیستی که برای ویدیو های خارجی زیرنویس فارسی درست کرد ؟؟؟

**Comment by msasanmh** [comment]
> > > سلام آقا خسته نباشید 
> > > من انگلیسی قوی ندارم میشه لطف کنید خودتون بگید این برنامه چیکار می‌کنه ؟؟؟ ویدیو بهش میدی زیرنویس درست می‌کنه برای هر ویدیویی!!!
> > 
> > نه، زیرنویس فارسی بهش میدی و اشکالات زیرنویس رو برات برطرف می‌کنه. 
> 
> خیلی ممنون جسارتا شما راهی بلد نیستی که برای ویدیو های خارجی زیرنویس فارسی درست کرد ؟؟؟

الان همه زیرنویس‌هایی که می‌بینید وجود داره، بدون استثنا همه مترجم‌ها از برنامه [Subtitle Edit](https://github.com/SubtitleEdit/subtitleedit) استفاده میکنن.
اگه منظورت ترجمه خودکار با هوش مصنوعی هستش که من اطلاعی در این مورد ندارم
